
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Ignite Frisco
subtitle: "A public speaking event."
url: "http://ignitefrisco.github.io" # the base hostname & protocol for your site
baseurl: "" # Set this value to "" if you want your site to be root
cover: "/assets/cover.png"
logo: "/assets/ignite-logo.PNG"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: noah
    desc: "Did all the stuff."
